Compute chunk size based on upload file size
genialis/resolwe-js pull request #130
Opened 2021-03-03 13:46 UTC by gregorjerse

2021-03-03 14:43 UTC, janybravo requested changes

2021-03-03 14:43 UTC, janybravo commented on src/core/services/api.ts
> +    private chunk_size: number;
Put that to local variable, less state to reason about.

2021-03-04 08:14 UTC, janybravo commented on src/core/services/api.ts
> +    private chunk_size: number;
Even better:
`resumeChunkSize: Math.max(this.MIN_CHUNK_SIZE, Math.floor(data.file.size / this.MAX_CHUNKS) + 1);`

2021-03-04 10:14 UTC, zigasinko approved these changes

2021-03-04 10:14 UTC, merged